---
name: Packaging problem report
description: Report problems with a package. This includes build failures or other issues related to a package. This is *not* for bugs with installed software.
labels: ["Package Problem", "Priority: Normal"]
title: "packagename: problem"
body:
  - type: checkboxes
    id: search
    attributes:
      label: Please confirm there isn't an existing open report for this package
      description: Before opening a new packaging problem report, please search [existing reports](https://github.com/getsolus/packages/labels/Package%20Problem%20Report) to ensure there is not an existing one.
        options:
          - label: I have searched through package problem reports
            required: true
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the package.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Summary of the problem
      description: Describe what's wrong with the package. Does it fail to build? Is the metadata incorrect? Something else?
      placeholder: ex. The foo package fails to build.
    validations:
      required: true
  - type: input
    id: details
    attributes:
      label: More information
      description: Details about the problem. ex. Errors in make output.
    validations:
      required: false